/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import GetData.GetFile;
import Model.Envio;
import Model.archivoVideo;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public final class Lista extends javax.swing.JFrame {

    /**
     * Creates new form Lista
     */
    public Lista() {
        initComponents();
        obtencionDia();        
        llenadoHoras();
        recargaLista();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    List<archivoVideo> file = new ArrayList<archivoVideo>();
    List<archivoVideo> hora = new ArrayList<archivoVideo>();

    //Método para recargar lista de reproducción
    public void recargaLista() {
        obtencionDia();        
        llenadoHoras();
        file = new GetFile().obtenerArchivo();
        llenadoTabla();
    }
    
    //Método para regresar la lista de horas
    public List mandarHoras(){
        return hora;
    }
    
    public void recargaHora(){
        hora = new GetFile().obtenerHora();  
        horaInicio = new int [hora.size()];
    }
    
    int horaInicio[];

    //Método para el llenado del vextor de la hora de inicio
    public void llenadoHoras() {
        String hour;
        recargaHora();        

        if (hora.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay listas cargadas en el servidor para este kiosko", "SIN LISTAS DE REPRODUCCION", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < hora.size(); i++) {
                hour = "" + hora.get(i).getHoraInicio() + hora.get(i).getMinutosInicio();
                horaInicio[i] = Integer.parseInt(hour);                
            }
            obtencionLista();
        }
    }

    //Método para conseguir la Lista de Reproduccion de ese momento 
    public void obtencionLista() {
        String hor = obtencionHora();
        String min = obtencionMinutos();
        String prueba = hor + min;        
        int hour = Integer.parseInt(prueba);
        Integer lista = 0, guardar = 0;

        for (int i = 0; i < horaInicio.length; i++) {            
            if (hour == horaInicio[i]) {
                lista = i;                
                break;
            } else {
                if (hour < horaInicio[i]) {
                    guardar = i;                    
                } else {
                    if (hour > horaInicio[i]) {
                        if (guardar == 0) {
                            lista = i;                            
                        } else {
                            lista = guardar;                            
                        }
                        break;
                    }
                }
            }
        }
        Envio.setHoraInicio(hora.get(lista).getHoraInicio());
        Envio.setMinutoInicio(hora.get(lista).getMinutosInicio());
    }

    //Método para llenado de la tabla 
    public void llenadoTabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        listaReproduccion.setModel(modelo);
        modelo.addColumn("Nombre");
        modelo.addColumn("Duración");
        modelo.addColumn("Posición");
        modelo.addColumn("Tipo");

        Object tab[] = new Object[4];

        for (int i = 0; i < file.size(); i++) {
            tab[0] = file.get(i).getNombre();
            tab[1] = file.get(i).getDuracion();
            tab[2] = file.get(i).getUbicacion();
            tab[3] = file.get(i).getTipo();
            modelo.addRow(tab);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaReproduccion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaReproduccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lista de Reproducción", "Videos", "Ubicación", "Duración"
            }
        ));
        jScrollPane1.setViewportView(listaReproduccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Calendar c = Calendar.getInstance();

    //Método para obtener el día del sistema
    public void obtencionDia() {
        String dia = "";          
        switch (c.get(Calendar.DAY_OF_WEEK)) {
            case 1:
                dia = "DOMINGO";
                break;

            case 2:
                dia = "LUNES";
                break;

            case 3:
                dia = "MARTES";
                break;

            case 4:
                dia = "MIERCOLES";
                break;

            case 5:
                dia = "JUEVES";
                break;

            case 6:
                dia = "VIERNES";
                break;

            case 7:
                dia = "SABADO";
                break;
        }
        Envio.setDia(dia);
    }

    //Método para obtener la hora del sistema
    public String obtencionHora() {
        return Integer.toString(c.get(Calendar.HOUR_OF_DAY));
    }

    //Método para obtener los minutos actuales del sistema
    public String obtencionMinutos() {
        return Integer.toString(c.get(Calendar.MINUTE));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Lista().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaReproduccion;
    // End of variables declaration//GEN-END:variables
}
