/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import GetData.GetFile;
import Model.Envio;
import Model.archivoVideo;
import java.awt.BorderLayout;
import java.awt.Dimension;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.Canvas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Timer;
import java.util.TimerTask;
import org.apache.commons.io.FilenameUtils;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.windows.Win32FullScreenStrategy;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;
import uk.co.caprica.vlcj.runtime.x.LibXUtil;

/**
 *
 * @author nipan
 */
public final class PantallaExclusiva extends javax.swing.JFrame {

    /**
     * Creates new form PantallaExclusiva
     */
    public PantallaExclusiva() {
        initComponents();
        tamañoPantalla();
        setLocationRelativeTo(null);
        this.setVisible(true);
        cambiarLibrerias();        
        reproducirVideo();
        //jPanel.add(jfxPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        video = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout videoLayout = new javax.swing.GroupLayout(video);
        video.setLayout(videoLayout);
        videoLayout.setHorizontalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        videoLayout.setVerticalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(video, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //private final JFXPanel jfxPanel = new JFXPanel();    
    int duracion;
    int archivo = -1;
    private EmbeddedMediaPlayerComponent player;
    
    //Método que ejecuta el video
    public void reproducirVideo() {
        /*Platform.runLater(new Runnable(){
            @Override
            public void run() {
                File file = new File ("C:\\Users\\mario\\Desktop\\SistemaMonitoreo\\Publicidad\\src\\Video\\SafeTaxi_Etapa_regional_ENEIT.mp4");
                //File file = new File("C:\\Users\\Jesús Mendoza\\Documents\\GitHub\\SistemaMonitoreo\\Publicidad\\src\\Video\\SafeTaxi_Etapa_regional_ENEIT.mp4");
                MediaPlayer oracleVid = new MediaPlayer(
                        new Media(file.toURI().toString())
                );
                jfxPanel.setScene(new Scene(new Group(new MediaView(oracleVid))));
                oracleVid.setVolume(0.7);
                //oracleVid.setCycleCount(MediaPlayer.INDEFINITE);
                oracleVid.play();
            }        
        });*/

        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
        EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer(new Win32FullScreenStrategy(this));
        player = new EmbeddedMediaPlayerComponent();
        //se añade reproductor 
        video.add(player);
        player.setSize(video.getSize());
        player.setVisible(true);       

        try {
            //Prepara el video a reproducir
            //File folder = new File("C:\\\\Users\\\\mario\\\\Desktop\\\\SistemaMonitoreo\\\\Publicidad\\\\src\\\\Video");
            //File folder = new File("http://192.168.1.139:1080/smp/Publicidad/src/Video/Kiosco_1");// + Envio.getKiosko());
            //File[] listOfFiles = folder.listFiles();           

            Envio envio = new Envio();
            
            file = new GetFile().obtenerArchivo(envio);

            for (int i = 0; i < file.size(); i++) {
                System.out.println(file.get(i).getUbicacion());
            }
            
            //cargarMedia(mediaPlayer);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        //mediaPlayer.prepareMedia("http://192.168.1.139:1080/smp/Publicidad/src/Video/Prueba.mp4"); //Servidor
        //Reproduce el video
        //mediaPlayer.play();        
    }

    List<archivoVideo> file = new ArrayList<archivoVideo>();

    //Método para obtener la ruta del archivo
    public String rutaArchivo() {
        String ruta = file.get(archivo).getUbicacion();

        Envio.setDuracion(file.get(archivo).getDuracion());
        return ruta;
    }

    //Método para saber la extensión del archivo
    public String extensionArchivo(String ruta) {
        //Obtiene la extensión del archivo        
        return FilenameUtils.getExtension(ruta);
    }

    //Método para cargar el video
    public void cargarMedia(EmbeddedMediaPlayer mediaPlayer) {
        archivo++;
        //mediaPlayer.prepareMedia("C:\\Users\\mario\\Desktop\\SistemaMonitoreo\\Publicidad\\src\\Video\\" + listOfFiles[archivo].getName());
        String ruta = rutaArchivo();
        String extension = extensionArchivo(ruta);

        //mediaPlayer.prepareMedia(ruta);
        player.getMediaPlayer().playMedia(ruta);
        //mediaPlayer.play();

        if (extension.equalsIgnoreCase("PNG") || extension.equalsIgnoreCase("ICO") || extension.equalsIgnoreCase("JPG") || extension.equalsIgnoreCase("BMP") || extension.equalsIgnoreCase("TIF")) {
            //Método que se ejecuta si es imagen el archivo
            
            
        } else {
            //Método que se ejecuta si el archivo es video
            player.getMediaPlayer().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
                @Override
                public void playing(MediaPlayer prueba) {
                    Timer timer = new Timer();
                    TimerTask task = new TimerTask() {
                        @Override
                        public void run() {
                            if (!prueba.isPlaying()) {
                                timer.cancel();                                
                            }
                        }
                    };
                    timer.schedule(task, 10, 1000);
                }

                @Override
                public void finished(MediaPlayer prueba) {
                    if (archivo == (file.size() - 1)) {
                        archivo = -1;
                        cargarMedia(mediaPlayer);
                        prueba.removeMediaPlayerEventListener(this);
                    } else {
                        cargarMedia(mediaPlayer);
                        System.out.println(archivo);
                        prueba.removeMediaPlayerEventListener(this);
                    }

                }

                @Override
                public void error(MediaPlayer prueba) {
                    cargarMedia(mediaPlayer);
                    prueba.removeMediaPlayerEventListener(this);
                }
            });
        }
    }

    //Método para leer librerias directas del VLC de 64 bits
    static void cambiarLibrerias() {
        NativeLibrary.addSearchPath(
                RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        LibXUtil.initialise();
    }

    //método para fijar el tamaño de la pantalla
    public void tamañoPantalla() {
        this.setSize(new Dimension(Envio.getAncho(), Envio.getAlto()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaExclusiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaExclusiva().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel video;
    // End of variables declaration//GEN-END:variables

}
